import { Nunito } from "next/font/google";
import "./globals.css";
const nunito = Nunito({
	subsets: ["latin"],
	style: ["normal"],
});

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={`${nunito.className} flex `}>
				{/* <SideBar/> */}
				{children}
			</body>
		</html>
	);
}